travis:
  secure:
    BINSTAR_TOKEN: f9ErUePPvoGoBFpH0FePuMtt6ivLabbjJb7+4E3PtjS3OFtXuD/mg80P+O6U4P13IBCMdl0Y3PgOfKHDAQCHUkOEJ9ZcKnHWOvLb/DKhVTNv9Uiz++TPjk6sV13REdaduW+DPVK3c8TYIO1WOF8BowxVYk6PXRfW0E4Be8X0docI0zY+e9i7UMbVKb5iDCB5R0bqb5f35N5RgMvfi7LbXD0Np6Fb8tWYcruhy4CsyFU6wDGsFN6/FwHFJNWaptS0dnvZ6387rIC0njMwvB4uNqp2PR/HGPhky/e1gHasHLBVPpXRkfNYl3xOcCraXeatomFsGBEczFEfVTM4cf/6mpjxxB3+c4++rz+C7sB8jrEj6rfZ2oSwm2oNSu8oMb2SFUQHwT5kdRohD1z0WuMtnizRXC0lbTchDg58KacK80hzcgDcVUTWgZJ3NP65coxANLCDqXzMLPMTgYHNxp3TTEC0HLajB4NRdWGRy7IOQl6DUgUlBVBj8BGzWb7a7P7zCp/gIDcA35TT9mSV/af669xWalkpZX3irxGqyvZ9oUQ9l1pP2qyYmsnJNfzl+jvxcfsQsh42hBq+x0MemcD2ir7B7dD/0VGEiIjIOkZs7dPxA0+80Nmp8NIla5J29qX1VpjHKgJOYjk07EjUbDbdZJVdQTwqWjsZjgAcUtXjQqo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
